### ISSUE TITLE
encrypt and decrypt data between python crypto package and dart steel_crypt

### ISSUE THREAD

**Issue by mrtnetwork** [AKushWarrior/steel_crypt#46]
hi
thank for your great package,
i need to encrypt and decrypt data between client(dart) and server(python)
can you give me  a tutorial for encrypt and decrypt data from aes-ctr in dart ,
in python i use  [Cryptodome](https://pycryptodome.readthedocs.io/en/latest/) package

# python code 
```
class MyCryptoData(object):

    def __init__(self, key):
        # encode key from string, and 16 byte==> 16 character like "backtorealityman"
        self.key = key.encode('utf-8')

    # encrypt data
    def encrypt_data(self, data):
        # crate new cipher with CTR mode
        cipher = AES.new(self.key, AES.MODE_CTR)
        # encrypt data with utf-8 encoding
        ct_bytes = cipher.encrypt(data.encode('utf-8'))
        # get nonce from created cipher and encode to base64 from utf8 decoding
        nonce = base64.b64encode(cipher.nonce).decode('utf-8')
        # convert encrypted file in base64 and decode from utf-8
        ct = base64.b64encode(ct_bytes).decode('utf-8')
        # save base64 nonce  and base64 encrypted file in json and return this file
        return json.dumps({'nonce': nonce, 'data': ct})

    def decrypt_data(self, data):
        # load encrypted data from json, nonce and encrypted file
        b64 = json.loads(data)
        # nonce from json
        nonce = base64.b64decode(b64['nonce'])
        # encrypted data from json
        ct = base64.b64decode(b64['data'])
        # decrypted with key, nonce and current mode CTR
        cipher = AES.new(self.key, AES.MODE_CTR, nonce=nonce)
        # its done, data encrypted and decrypted correct
        return cipher.decrypt(ct)


```

**Comment by AKushWarrior** [comment]
You'll need to look into the AesCrypt or AesCryptRaw class in the API reference. You can find that API reference on https://pub.dev/packages/steel_crypt.

The AesCrypt class takes in UTF-8 inputs and returns base64, so porting these functions should be pretty simple. Note that AesCrypt requires a base64 key, not a UTF8 one. So that might be an issue.

Alternatively, for a more direct port from your Python class, you can use AesCryptRaw. AesCryptRaw just takes in Lists of bytes (Uint8List, meaning unsigned 8 bit integers, meaning one byte) and outputs lists of bytes. It assumes that you will take care of encoding (you can use the standard library dart:convert for that).
